<style>
    .grid-title {
        display: none;
    }
    .navbar {
     display: none;   
    }
    .CANCELADO{
    background: #D3D3D3;
    //background: #EC974D;
        
    }
</style>
<div>
    <?php echo $this->mensaje; ?><?php echo $this->baseUrl; ?>
    <h2>Hola mama esto es una prueba</h2>
</div>

<script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/activos/activos-index.js"></script>
