
<div>
    <label class="tittle_iframe">Listado Tracking </label>
</div>

<!-- Button trigger modal -->
<div class="btn-group" role="group" aria-label="">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" > <span class="glyphicon glyphicon-plus"></span> Registrar</button>
    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-download-alt"></span> PDF</button>
    <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-download-alt"></span> Excel</button>
</div>

<div>
    <table id="jqGrid"></table>
    <div id="jqGridPager"></div>
</div>


<!--Libreria Jquery -->
<link rel="stylesheet"  href="<?php echo $this->baseUrl; ?>/css/activoEstilo.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/lib/bootstrap3/jquery-ui.css">
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/lib/bootstrap3/jquery.js"></script>

<!-- jqModalBootstrap -->
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/lib/bootstrap3/bootstrap.min.css">
<script src="<?php echo $this->baseUrl; ?>/lib/bootstrap3/bootstrap.min.js"></script>

<!--Libreria JqGRID -->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/lib/jqgrid/css/ui.jqgrid.css">
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/lib/jqgrid/js/i18n/grid.locale-es.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/lib/jqgrid/js/jquery.jqGrid.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/activos/procTracking.js"></script>

<!--jqValidate-->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/lib/jqValidate/estilos.css">
<script src="<?php echo $this->baseUrl; ?>/lib/jqValidate/jquery.form.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/lib/jqValidate/jquery.validate.js" type="text/javascript"></script>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button id="btnCerrar" name="btnCerrar" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"> Nueva Solicitud </h4>
            </div>
            <div class="modal-body">
                <form id="formTracking" name="formTracking"  method="post">
                    <input id="inpIdEstatus" name="inpIdEstatus" type="hidden" value="1" />
                    <input id="inpIdEstatusDetalle" name="inpIdEstatusDetalle" type="hidden" value="1" />

                    <div class="form-group">
                        <label for="recipient-name" class="control-label"><span class="label-oblig">( * )</span> Categoria Activo:</label>
                        <div class="input-group col-sm-12">
                            <select id="inpCategoria" name="inpCategoria" class="form-control" >
                                <option value=""  selected>[Seleccione]</option>
                            </select>

                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                    <div class="form-group">
                        <label for="recipient-name" class="control-label"><span class="label-oblig">( * )</span> Sub Categoria Activo:</label>
                        <div class="input-group col-sm-12">
                            <select id="inpSubCategoria" name="inpSubCategoria" class="form-control" >
                                <option value=""  selected>[Seleccione]</option>
                            </select>

                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <div class="form-group">
                        <label for="recipient-name" class="control-label"><span class="label-oblig">( * )</span> Cantidad:</label>
                        <div class="input-group col-sm-12">
                            <select id="inpCantidad" name="inpCantidad" class="form-control" >
                                <option value="1" selected >1</option>
                                <option value="2"  >2</option>
                                <option value="3"  >3</option>
                                <option value="4"  >4</option>
                                <option value="5"  >5</option>
                                <option value="6"  >6</option>
                                <option value="7"  >7</option>
                                <option value="8"  >8</option>
                                <option value="9"  >9</option>
                                <option value="10"  >10</option>
                            </select>

                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <div class="form-group">
                        <label for="recipient-name" class="control-label"><span class="label-oblig">( * )</span> Motivo de la Solicitud:</label>
                        <div class="input-group col-sm-12">
                            <select id="inpMotivoSolicitud" name="inpMotivoSolicitud" class="form-control" >
                                <option value=""  selected>[Seleccione]</option>
                            </select>

                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>
                    <div class="form-group ">
                        <label for="recipient-name" class="control-label"><span class="label-oblig">( * )</span> Describe el Motivo:</label>
                        <div class="input-group col-sm-12">
                            <textarea id="areaDesSolicitud" name="areaDesSolicitud" class="form-control soloLetras"></textarea>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <button id="btnGuardar" type="submit" class="btn btn-primary">Enviar Solicitud </button>

                </form>
            </div>
            <div class="modal-footer">
                <span class="label-oblig-desc"> Lo campos con asteriscos (*) son obligatorios </span>
                <span class="label-oblig-desc msjRespuesta text-center"> </span>
            </div>
        </div>
    </div>
</div>