
<div>
    <label class="tittle_iframe">Listado de Activos </label>
</div>

<div class="btn-group" role="group" aria-label="">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" > <span class="glyphicon glyphicon-plus"></span> Registrar</button>
    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-download-alt"></span> PDF</button>
    <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-download-alt"></span> Excel</button>
</div>

<div>
    <table id="jqGridListActivo"></table>
    <div id="jqGridPagerListActivo"></div>
</div>


<!--Libreria Jquery-->
<link rel="stylesheet"  href="<?php echo $this->baseUrl; ?>/css/activoEstilo.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/lib/bootstrap3/jquery-ui.css">
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/lib/bootstrap3/jquery.js"></script>

<!-- jqModalBootstrap -->
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/lib/bootstrap3/bootstrap.min.css">
<script src="<?php echo $this->baseUrl; ?>/lib/bootstrap3/bootstrap.min.js"></script>

<!--Libreria JqGRID -->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/lib/jqgrid/css/ui.jqgrid.css">
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/lib/jqgrid/js/i18n/grid.locale-es.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/lib/jqgrid/js/jquery.jqGrid.min.js"></script>

<!--jqValidate-->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/lib/jqValidate/estilos.css">
<script src="<?php echo $this->baseUrl; ?>/lib/jqValidate/jquery.form.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/lib/jqValidate/jquery.validate.js" type="text/javascript"></script>

<!--jqCalendario-->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/lib/jqCalendario/bootstrap-datetimepicker.min.css">
<script src="<?php echo $this->baseUrl; ?>/lib/jqCalendario/moment.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/lib/jqCalendario/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/lib/jqCalendario/bootstrap-datetimepicker.es.js" type="text/javascript"></script>

<!-- jq-Dialog -->
<link href="<?php echo $this->baseUrl; ?>/lib/jqDialog/bootstrap-dialog.min.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl; ?>/lib/jqDialog/bootstrap-dialog.min.js" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/activos/procListActivoMain.js"></script>

<!--Modal Para Registar-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

            <form id="formAgregarActivo" name="formAgregarActivo" class="form-horizontal" action="#" method="post">
                <!-- CAMPO Ocultos  -->
                <input id="inptEstatus" name="inptEstatus" type="hidden" value="1">
                <input id="inptProceso" name="inptProceso" type="hidden"  value="Guardar">
                <input id="inpReferencia" name="inpReferencia" type="hidden"  value="-" >
                <input id="inpId" name="inpId" type="hidden"  value="" >


                <div class="modal-header">
                <button id="btnCerrar" name="btnCerrar" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"> <span id="spTitulomodal"> Registrar </span> activo</h4>
            </div>
            <div class="modal-body">

                    <div class="panel panel-info">
                        <div class="panel-heading">Características del Activo</div>
                        <div class="panel-body">
                            <!-- Grupo  0   -->
                            <div class="row">

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span> Tipos de activos:</label>
                                    <div class="input-group col-sm-7">
                                        <select id="inptTiposActivos" name="inptTiposActivos" class="form-control" >
                                            <option value=""  selected>[Seleccione]</option>
                                            <option value="1">1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->
                                </div>

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Tipo de asignación:</label>
                                    <div class="input-group col-sm-7">
                                        <select id="inptAsignacion" name="inptAsignacion" class="form-control" >
                                            <option value=""  selected>[Seleccione]</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->
                                </div>

                            </div>
                            <!-- Grupo  0   -->

                            <!-- Grupo  1   -->
                            <div class="row">

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Categoría:</label>
                                    <div class="input-group col-sm-7">
                                        <select id="inptCategoria" name="inptCategoria" class="form-control" >
                                            <option value=""  selected>[Seleccione]</option>
                                            <option value="1">1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->
                                </div>

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Sub-categoria:</label>
                                    <div class="input-group col-sm-7">
                                        <select id="inptSubCategoria" name="inptSubCategoria" class="form-control" >
                                            <option value=""  selected>[Seleccione]</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->
                                </div>

                            </div>
                            <!-- Grupo  1   -->

                            <!-- Grupo  2   -->
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Estado físico:</label>
                                    <div class="input-group col-sm-7">
                                        <select id="inptEstadoFisico" name="inptEstadoFisico" class="form-control" >
                                            <option value=""  selected>[Seleccione]</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->
                                </div>

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Proveedor:</label>
                                    <div class="input-group col-sm-7">
                                        <select id="inptProveedor" name="inptProveedor" class="form-control" >
                                            <option value=""  selected>[Seleccione]</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                            </div>
                            <!-- Grupo  2   -->

                            <!-- Grupo  3   -->
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Marca:</label>
                                    <div class="input-group col-sm-7">
                                        <input id="inptMarca" name="inptMarca" type="text" class="form-control"/>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover"><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Modelo:</label>
                                    <div class="input-group col-sm-7">
                                        <input id="inptModelo" name="inptModelo" type="text" class="form-control"/>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                            </div>
                            <!-- Grupo  3   -->

                            <!-- Grupo  4   -->
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>No. Serie:</label>
                                    <div class="input-group col-sm-7">
                                        <input id="inptSerie" name="inptSerie" type="text" class="form-control"/>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Cod. barras pendulum:</label>
                                    <div class="input-group col-sm-7">
                                        <input id="inptCoBarras" name="inptCoBarras" type="text" class="form-control"/>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                            </div>
                            <!-- Grupo  4   -->

                            <!-- Grupo  5   -->
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>No. factura:</label>
                                    <div class="input-group col-sm-7">
                                        <input id="inptFactura" name="inptFactura" type="text" class="form-control"/>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Fecha de compra: </label>
                                    <div class="input-group col-sm-7">
                                        <input id="inptFechaCompra" name="inptFechaCompra" type="text" class="form-control hasDatepicker"/>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                            </div>
                            <!-- Grupo  5   -->



                            <!-- Grupo  6   -->
                            <div class="row">

                                <div class="form-group col-lg-12">
                                    <label class="col-sm-2 control-label" for="comment"><span class="label-oblig">( * )</span>Descripción Activo:</label>
                                    <div class="input-group col-sm-9">
                                        <textarea id="areaDesActivo" name="areaDesActivo" class="form-control" rows="3" ></textarea>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover"><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->
                                </div>

                            </div>
                            <!-- Grupo  6   -->

                        </div>
                    </div>


                    <div class="panel panel-info">
                        <div class="panel-heading"><span class="label-oblig">( * )</span>Ubicación del Activo</div>
                        <div class="panel-body">
                            <!-- Grupo  1   -->
                            <div class="row">

                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label">Usuario:</label>
                                    <div class="input-group col-sm-7">
                                        <input id="inptUsuario" name="inptUsuario" type="text" class="form-control"/>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>


                                <div class="form-group col-lg-6">
                                    <label class="col-sm-4 control-label"><span class="label-oblig">( * )</span>Sucursal:</label>
                                    <div class="input-group col-sm-7">
                                        <select id="inptIdSucursal" name="inptIdSucursal" class="form-control" >
                                            <option value=""  selected>[Seleccione]</option>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                        </select>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                            </div>
                            <!-- Grupo  1   -->

                            <!-- Grupo  2  -->
                            <div class="row">

                                <div class="form-group col-lg-12">
                                    <label class="col-sm-2 control-label" for="comment"><span class="label-oblig">( * )</span>Descripción Ubicación:</label>
                                    <div class="input-group col-sm-9">
                                        <textarea id="areaDesUbicacion" name="areaDesUbicacion" class="form-control" rows="3" ></textarea>
                                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover"><i class="glyphicon glyphicon-alert"></i></span>
                                    </div>
                                    <!-- Componente Mesj-->
                                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                                    </div>
                                    <!-- Componente Mesj-->

                                </div>

                            </div>
                            <!-- Grupo  2   -->

                        </div>
                    </div>
                <button id="btnGuardar" type="submit" class="btn btn-info"><span id="bntTitulomodal"> Registrar </span> </button>



            </div>
            <div class="modal-footer">

                <span class="label-oblig-desc"> Lo campos con asteriscos (*) son obligatorios </span>
                <span class="label-oblig-desc msjRespuesta text-center"> </span>

            </div>
        </form>
        </div>
    </div>
</div>

