<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!--jqValidate-->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/lib/jqValidate/estilos.css">
<script src="<?php echo $this->baseUrl; ?>/lib/jqValidate/jquery.form.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/lib/jqValidate/jquery.validate.js" type="text/javascript"></script>

<!--jqCalendario-->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/lib/jqCalendario/bootstrap-datetimepicker.min.css">
<script src="<?php echo $this->baseUrl; ?>/lib/jqCalendario/moment.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/lib/jqCalendario/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/lib/jqCalendario/bootstrap-datetimepicker.es.js" type="text/javascript"></script>

<!-- jq-Dialog -->
<link href="<?php echo $this->baseUrl; ?>/lib/jqDialog/bootstrap-dialog.min.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl; ?>/lib/jqDialog/bootstrap-dialog.min.js" type="text/javascript"></script>

<!--Js Formulario Activo-->
<script src="<?php echo $this->baseUrl; ?>/js/activos/formActivo.js" type="text/javascript"></script>

<form id="formAgregarActivo" name="formAgregarActivo" class="form-horizontal" action="#" method="post">
    <div class="panel panel-info">
        <div class="panel-heading">Características del Activo</div>
        <div class="panel-body">
                <!-- Grupo  1   -->
                <div class="row">

                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Tipos de activos:</label>
                        <div class="input-group col-sm-7">
                            <select id="inptTiposActivos" name="inptTiposActivos" class="form-control" >
                                <option value=""  selected>[Seleccione]</option>
                                <option value="1">1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                            </select>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Tipo de asignación:</label>
                        <div class="input-group col-sm-7">
                            <select id="inptAsignacion" name="inptAsignacion" class="form-control" >
                                <option value=""  selected>[Seleccione]</option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                            </select>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                </div>
                <!-- Grupo  1   -->

                <!-- Grupo  2   -->
                <div class="row">
                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Estado físico:</label>
                        <div class="input-group col-sm-7">
                            <select id="inptEstadoFisico" name="inptEstadoFisico" class="form-control" >
                                <option value=""  selected>[Seleccione]</option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                            </select>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Proveedor:</label>
                        <div class="input-group col-sm-7">
                            <select id="inptProveedor" name="inptProveedor" class="form-control" >
                                <option value=""  selected>[Seleccione]</option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                            </select>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                </div>
                <!-- Grupo  2   -->

                <!-- Grupo  3   -->
                <div class="row">
                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Marca:</label>
                        <div class="input-group col-sm-7">
                            <input id="inptMarca" name="inptMarca" type="text" class="form-control"/>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover"><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Modelo:</label>
                        <div class="input-group col-sm-7">
                            <input id="inptModelo" name="inptModelo" type="text" class="form-control"/>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                </div>
                <!-- Grupo  3   -->

                <!-- Grupo  4   -->
                <div class="row">
                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">No. Serie:</label>
                        <div class="input-group col-sm-7">
                            <input id="inptSerie" name="inptSerie" type="text" class="form-control"/>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Cod. barras pendulum:</label>
                        <div class="input-group col-sm-7">
                            <input id="inptCoBarras" name="inptCoBarras" type="text" class="form-control"/>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                </div>
                <!-- Grupo  4   -->

                <!-- Grupo  5   -->
                <div class="row">
                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">No. factura:</label>
                        <div class="input-group col-sm-7">
                            <input id="inptFactura" name="inptFactura" type="text" class="form-control"/>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                    <div class="form-group col-lg-6">
                        <label class="col-sm-4 control-label">Fecha de compra: </label>
                        <div class="input-group col-sm-7">
                            <input id="}" name="inptFechaCompra" type="text" class="form-control hasDatepicker"/>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                    </div>

                </div>
                <!-- Grupo  5   -->

                <!-- Grupo  6   -->
                <div class="row">

                    <div class="form-group col-lg-12">
                        <label class="col-sm-2 control-label" for="comment">Descripción Activo:</label>
                        <div class="input-group col-sm-9">
                            <textarea id="areaDesActivo" name="areaDesActivo" class="form-control" rows="3" ></textarea>
                            <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover"><i class="glyphicon glyphicon-alert"></i></span>
                        </div>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                </div>
                <!-- Grupo  6   -->

        </div>
    </div>


    <div class="panel panel-info">
        <div class="panel-heading">Ubicación del Activo</div>
        <div class="panel-body">
            <!-- Grupo  1   -->
            <div class="row">

                <div class="form-group col-lg-6">
                    <label class="col-sm-4 control-label">Usuario:</label>
                    <div class="input-group col-sm-7">
                        <input id="inptUsuario" name="inptUsuario" type="text" class="form-control"/>
                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                    </div>
                    <!-- Componente Mesj-->
                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                    </div>
                    <!-- Componente Mesj-->

                </div>


                <div class="form-group col-lg-6">
                    <label class="col-sm-4 control-label">Sucursal:</label>
                    <div class="input-group col-sm-7">
                        <select id="inptIdSucursal" name="inptIdSucursal" class="form-control" >
                            <option value=""  selected>[Seleccione]</option>
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                        </select>
                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover" ><i class="glyphicon glyphicon-alert"></i></span>
                    </div>
                    <!-- Componente Mesj-->
                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                    </div>
                    <!-- Componente Mesj-->

                </div>

            </div>
            <!-- Grupo  1   -->

            <!-- Grupo  2  -->
            <div class="row">

                <div class="form-group col-lg-12">
                    <label class="col-sm-2 control-label" for="comment">Descripción Ubicación:</label>
                    <div class="input-group col-sm-9">
                        <textarea id="areaDesUbicacion" name="areaDesUbicacion" class="form-control" rows="3" ></textarea>
                        <span class="input-group-addon" data-toggle="popover" title="Información" data-content="Some content inside the popover"><i class="glyphicon glyphicon-alert"></i></span>
                    </div>
                    <!-- Componente Mesj-->
                    <div class="error" style="display:none"> <b class="border-notch notch"></b>
                    </div>
                    <!-- Componente Mesj-->

                </div>

            </div>
            <!-- Grupo  2   -->

        </div>
    </div>
    <div class="row">
        <div class="col-sm-4" >
         &nbsp;
        </div>
        <div class="col-sm-4" style="text-align:center;">
            <button type="submit" class="btn btn-info btn-md btn-block">Guardar</button>
        </div>
        <div class="col-sm-4">
            &nbsp;

        </div>
    </div>
</form>

<button id="btnLeonard" class="btn btn-primary">Run the code</button>
